### PR TITLE
Added identity hash

### PR DESCRIPTION
**Pull request by filiplazovic**

### CODE REVIEW

**Comment by weikengchen** [comment]
One question about the use case: do you want a Merkle tree where the leaf is a field element? From the test example, it seems to be the case.

There is an issue related to soundness. Note that the number of input bits in the code is `F::BigInt::NUM_LIMBS * 64`, but the field element cannot indeed represent this number of bits (e.g., a field of 260 bits have 5 limbs, but it cannot represent 320 bits). We may need to bound this number.

**Comment by weikengchen** [comment]
As for the former, I think it is a problem that currently Merkle tree is taking `ToBytes` as leaves and the developers have no other choices, and this is a restriction because one using Poseidon would prefer Merkle tree that takes field elements directly as leaves, rather than being forced to bypass this conversion. I will need to think about what is the best way to handle this...

**Comment by filiplazovic** [comment]
@weikengchen It would def have been easier if we could have Poseidon itself take field elements and return field elements, as well as the leaf being the field element

**Comment by weikengchen** [comment]
Let me @tsunrise. I think the difficult part is to design an interface that is general enough as well as not prohibiting optimization.

**Comment by tsunrise** [comment]
@filiplazovic I've updated merkle tree API in #60, which can support leaf as field element (given a CRH whose `Input` is field element). Is identity hash still needed?

**Pull request closed without merging**
