### PR TITLE
Correctly absorb curve points into cryptographic sponge

### PR DESCRIPTION
**Pull request by slumber**
## Description

Tests prove that they don't match. 0-case for SW curve won't pass still because it requires changes to r1cs-std.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (main)
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by Pratyush** [comment]
Now that the PR to r1cs-std is merged, how should this proceed?

**Comment by slumber** [comment]
> Now that the PR to r1cs-std is merged, how should this proceed?

Should I add `[patch.crates-io]`?

**Comment by Pratyush** [comment]
Yes let's patch

**Comment by slumber** [comment]
@Pratyush is it good to merge?

**Review by Pratyush — APPROVED** [review]

**Pull request merged**
