### PR TITLE
Fix according to breaking changes in `r1cs-std`

### PR DESCRIPTION
**Pull request by autquis**
Just a refactor according to arkworks-rs/r1cs-std#135 (and see the comment below)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (main)
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by autquis** [comment]
Now, this PR is also a refactor according to breaking changes in arkworks-rs/r1cs-std#121

**Review by Pratyush — APPROVED** [review]
Looks good.

**Comment by autquis** [comment]
Thanks for merging! @Pratyush 
However, I did not see that arkworks-rs/r1cs-std#136 got merged, so the `Cargo.toml` is incorrect now. (I wanted to update it after `add-convert-traits-to-prelude` getting merged). Could you update it, please?

**Comment by Pratyush** [comment]
Oops, made a new PR #127 to fix it.

**Pull request merged**
