### PR TITLE
Basic elgamal encryption gadget

### PR DESCRIPTION
**Pull request by sam-steffen**
I implemented a basic ElGamal encryption gadget for #21.
Does this look ok?

### CODE REVIEW

**Comment by weikengchen** [comment]
I have the following concern:

Note that Jubjub is a curve with cofactor 8, which means that the generator of Jubjub forms a group that is not prime-order. This may affect the security guarantee of ElGamal---it requires a prime-order group/subgroup.

One solution, which we are likely going to do, is that our ElGamal always clears the cofactor. That is, instead of choosing a random generator for the ElGamal encryption,
```
let generator = C::rand(rng).into();
```
we always multiply this generator by the cofactor.

Or, we can insist on existing groups where the cofactor is 1. Very few curves in `arkworks/curves` satisfy this requirement, but G_1 of BN254 satisfies this: https://github.com/arkworks-rs/curves/blob/master/bn254/src/curves/g1.rs. But this is not a TE curve so the performance suffers. It seems that, when people are searching for TE curves, many curves naturally have some cofactors.

Now, the second part.

If we clear the cofactor of the generator, we also need to handle the "cofactor" that the plaintext may have. That is, plaintext, which currently consists of group elements, must also be in the prime-order subgroup.

We could not simply multiply the plaintext with the cofactor---decryption would be extremely challenging.

At this moment, maybe all we need to do is to add sanity checks---only allowing plaintext in which all elements are inside the subgroup. This check does not need to be included in the constraint system but can be done outside, and we may have an `unchecked` version of encryption that disables this check.

**Comment by sam-steffen** [comment]
Yes, we have to be careful to remain in the prime-order subgroup of JubJub, e.g. using cofactor multiplication. However, I believe the call `let generator = C::rand(rng).into();` already does this and hence yields a safe generator? See: https://github.com/arkworks-rs/algebra/blob/master/ec/src/models/twisted_edwards_extended.rs#L359

Regarding the embedding of plaintext in the subgroup: I agree we should add an according sanity check (e.g., multiplying `plaintext` by the subgroup order) in the `encrypt` function. How to embed an actual bitstring message is indeed a separate concern.

**Comment by weikengchen** [comment]
You are right. The `C::rand` would scale the element by the cofactor. So this part is done.

Regarding the sanity check, we can use `is_in_correct_subgroup_assuming_on_curve`.

**Comment by ValarDragon** [comment]
Should we be exposing El-Gamal, versus something like Cramer-Shoup?

(I don't feel too great about only exposing something that isn't CCA secure)

**Comment by weikengchen** [comment]
I think exposing ElGamal is good since in many applications CPA security suffices. And Cramer-Shoup has additional overhead that such applications may want to avoid.

**Comment by sam-steffen** [comment]
I think having multiple encryption schemes with different properties is valuable (ultimately, the user of the library should decide).

Regarding the sanity check: I just noticed that `ProjectiveCurve::Affine` (which is used as the plaintext type for the ElGamal implementation) has a bound on `AffineCurve` which, according to its documentation, already guarantees that the point lies in the correct prime order subgroup. So I believe no check is needed.

**Comment by weikengchen** [comment]
I agree. I checked the code. Even if the element is from outside (allocated via canonical deserialization), there is a check for subgroup membership.

https://github.com/arkworks-rs/algebra/blob/e7eeea3f2ac7d621f68089b978097403dd02e91b/ec/src/models/twisted_edwards_extended.rs#L784

**Pull request merged**
